name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


env:
  API_URL: "http://localhost:7081"
  WEB_URL: "https://ecommerce-playground.lambdatest.io"
  WEB_USER_EMAIL: "dummy1234@gmail.com"
  WEB_USER_PASSWORD: "dummy1234@gmail.com"
  HEADLESS: "true"

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Start API server
      run: |
        nohup java -jar api/demo-0.0.1-SNAPSHOT.jar &
        sleep 10

    - name: Run tests
      run: |
        npm install
        npm test

    - name: Prepare Allure results
      run: |
        mkdir -p gh-pages/allure-results
        cp -r allure-results/* gh-pages/allure-results/

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: gh-pages/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history